development:
  adapter: mysql2
  encoding: utf8
  database: noeh
  username: noeh
  password: noeh
  host: 127.0.0.1
  port: 3306

production: 
  adapter: mysql2
  database: noeh
  username: noeh
  host: localhost
  password: ChimbraGalera2
  port: 3306
  pool: 5
  timeout: 5000